// template-package-vue-ts/src/MyButton.vue
<script setup lang="ts">
import { ref } from "vue";

const props = defineProps<{
  type?: "primary";
}>();

const { type } = props;

const count = ref(0);
</script>

<template>
  <button class="my-button" @click="count++">
    my button<br />
    type: {{ type }}<br />
    count: {{ count }}
  </button>
</template>

<style scoped>
.my-button {
  padding: 8px 16px;
}
</style>

// template-package-react-ts/src/MyButton.tsx
import React, { useState } from "react";
import style from "./style.module.css";

interface MyButtonProps {
  type?: "primary";
}

export const MyButton: React.FC<MyButtonProps> = ({ type }) => {
  const [count, setCount] = useState(0);
  return (
    <button className={style.myButton} onClick={() => setCount(count + 1)}>
      my button
      <br /> type: {type}
      <br /> count: {count}
    </button>
  );
};
